window.FOUNDR_DATA = (() => {
  const vendors = [
    ['NLK','Nasi Lemak Kita','Food & Beverage','Operate','1,842',12,'Today, 4:21 PM','Active'],['KJ','Kopi Jalanan','Beverage','Grow','1,291',8,'Today, 3:10 PM','Active'],['AB','ABC Bakery','Bakery','Grow','923',6,'Yesterday','Active'],['AGS','Ayam Gepuk Station','Food & Beverage','Operate','874',9,'Today, 1:02 PM','Active'],['SB','Sweet Bites','Bakery','Free','412',4,'2 days ago','At Risk'],['BF','Bloom Florist','Florist & Gifts','Grow','381',5,'Today, 11:46 AM','Active'],['DF','Daily Fresh','Groceries','Free','206',3,'3 days ago','At Risk'],['QM','Quick Mart','Retail','Trial','174',2,'Today, 9:12 AM','Active'],['MB','MealBox MY','Meal Prep','Grow','612',7,'Yesterday','Active'],['UB','Urban Bites','Catering','Free','98',2,'5 days ago','Suspended'],['DK','Dapur Kita','Meal Prep','Operate','512',6,'23 Apr 2025','Active'],['TE','Teh Tarik Express','Food & Beverage','Grow','324',5,'24 Apr 2025','Active']
  ].map((v,i)=>({id:i+1,initials:v[0],name:v[1],industry:v[2],plan:v[3],orders:v[4],drivers:v[5],last:v[6],status:v[7]}));
  const runs = vendors.slice(0,10).map((v,i)=>({id:`RUN-${1192+i}`,vendor:v.name,initials:v.initials,driver:['Ali Rahman','Mei Ling','Kamal','Rizal','Suresh','Arman','Daniel','Hafiz','Firman','Zul'][i],vehicle:['Motorcycle','Van','Car'][i%3],stops:[14,21,18,9,11,16,20,13,8,12][i],done:[8,16,3,7,0,12,20,5,0,10][i],eta:['12:20 PM','1:05 PM','2:40 PM','11:50 AM','11:30 AM','12:10 PM','10:58 AM','1:45 PM','12:00 PM','12:35 PM'][i],status:['In Delivery','In Delivery','In Delivery','Attention','Not Started','In Delivery','Completed','In Delivery','Not Started','In Delivery'][i],issues:[0,1,0,2,0,0,0,1,0,0][i]}));
  const tickets = [
    ['#48321','Customer not reachable','Delivery Issue','Farah Izzati','Nasi Lemak Kita','High','Open','2h ago'],['#48320','App crash on login','Technical','Ali Rahman','—','High','In Progress','3h ago'],['#48319','Wrong item received','Order Issue','Jason Lee','MealBox MY','Medium','Open','4h ago'],['#48318','Zone not updating','Account','ABC Bakery','ABC Bakery','Medium','In Progress','5h ago'],['#48317','Payout not received','Payment','Kumar','—','High','Waiting','6h ago'],['#48316','Track link not working','Tracking','Siti Nadia','Bloom Florist','Medium','Open','8h ago'],['#48315','Add new driver','Account','Daily Fresh','Daily Fresh','Low','Resolved','12h ago'],['#48314','Map location incorrect','Map / GPS','Hafiz','—','Medium','In Progress','14h ago'],['#48313','Feature request','Feedback','Quick Mart','Quick Mart','Low','Open','16h ago'],['#48312','Slow loading dashboard','Performance','Kopi Jalanan','—','Low','Resolved','18h ago']
  ].map((x,i)=>({id:x[0],subject:x[1],type:x[2],from:x[3],vendor:x[4],priority:x[5],status:x[6],updated:x[7],channel:i%2?'Email':'WhatsApp'}));
  const services=['Vendor Web','Mobile API','Driver App','Customer Tracking','Database','Storage','Auth','Notification','n8n Automation','Payment Gateway','Map & Routing','CDN / Assets'].map((name,i)=>({name,detail:['vendor.cefflo.com','api.cefflo.com','driver.cefflo.com','track.cefflo.com','Primary DB','File storage','Authentication','Email / SMS / Push','Marketing & Ops','Billing & Subscription','Maps, Geocoding, Routes','Static Assets'][i],uptime:['100.0%','99.98%','99.96%','99.99%','99.99%','99.98%','99.99%','99.97%','99.95%','99.98%','99.96%','99.99%'][i],response:['850 ms','1.1 s','1.3 s','920 ms','68 ms','120 ms','140 ms','310 ms','640 ms','380 ms','520 ms','230 ms'][i],status:'Healthy'}));
  const logs=['Updated delivery zone settings','Created new delivery run','Run status changed to In Delivery','Generated delivery plan','User logged in','Updated driver profile','Removed customer record','GET /orders 200 OK','Workflow: Dispatch Notification','Changed subscription plan'].map((details,i)=>({time:`24 Apr 2025, ${['4:32','4:28','4:17','4:12','3:58','3:46','3:32','3:21','3:05','2:48'][i]} PM`,user:['Admin','Mei Ling','Driver App','System','Farah Izzati','Kumar','Jason Lee','API','n8n Automation','Admin'][i],action:['Updated','Created','Status Update','Scheduled','Login','Updated','Deleted','API Access','Executed','Updated'][i],details,module:['Vendor','Operations','Driver','System','Auth','Driver','Customer','API','Integrations','Business'][i],status:'Success'}));
  const campaigns=[['Meal Prep Owners','Meta Ads','RM 620',81,6,'4.1x','Performing'],['Bakery Delivery','Meta Ads','RM 540',62,4,'3.0x','Performing'],['Local Business Growth','TikTok Ads','RM 430',72,3,'2.1x','Average'],['Florist & Gift','Google Ads','RM 520',44,2,'1.1x','Review']].map(x=>({name:x[0],channel:x[1],spend:x[2],leads:x[3],paid:x[4],roas:x[5],status:x[6]}));
  return {vendors,runs,tickets,services,logs,campaigns};
})();
