'use client';
import {useMemo,useState} from 'react';
import {ArrowLeft,Bell,Bike,Building2,Check,ChevronDown,ChevronRight,CircleHelp,Clock3,Eye,Grid2X2,LifeBuoy,LockKeyhole,Map,Menu as MenuIcon,Package,Plus,Search,Settings,ShieldCheck,Sun,UserRound,X,Zap} from 'lucide-react';
import {scene,scenes,Scene} from './scenes';

const orders=[['#CF-1048','Taman Melati',3,'READY'],['#CF-1047','Setapak',2,'READY'],['#CF-1046','Wangsa Maju',4,'ONGOING'],['#CF-1045','Gombak',1,'DONE']].map(([id,place,items,status])=>({id:String(id),place:String(place),items:Number(items),status:String(status)}));
const deliveries=[['Zone North','Amir',7,'ON ROUTE'],['Zone Central','Hafiz',5,'COMPLETED'],['Zone South','Aiman',4,'READY']];
const riders=[['Amir','Motorcycle','On delivery'],['Hafiz','Car','Available'],['Aiman','Motorcycle','Available'],['Farid','Van','Offline']];
type Props={open:(id:string)=>void};
function Status({children}:{children:string}){const live=['READY','ON ROUTE','ONGOING','AVAILABLE','ACTIVE'].includes(children.toUpperCase());return <span className={'status '+(live?'live':'')}>{children}</span>}
function Header({s,back,onIndex}:{s:Scene,back?:()=>void,onIndex:()=>void}){return <header><div className="head-title">{back&&<button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button>}<div><span className="screen-id">{s.id}</span><h1>{s.title}</h1></div></div><button className="scene-count" onClick={onIndex}>60 scenes <Grid2X2/></button></header>}
function Row({title,sub,status,onClick,Icon}:{title:string,sub?:string,status?:string,onClick?:()=>void,Icon?:typeof Package}){return <button className="row" onClick={onClick}>{Icon&&<span className="row-icon"><Icon/></span>}<span className="row-copy"><b>{title}</b>{sub&&<small>{sub}</small>}</span>{status&&<Status>{status}</Status>}<ChevronRight className="chev"/></button>}
function Section({title,action}:{title:string,action?:()=>void}){return <div className="section-title"><h2>{title}</h2>{action&&<button onClick={action}>See All <ChevronRight/></button>}</div>}
function Info({rows}:{rows:[string,string][]}){return <div className="info">{rows.map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}
function Tabs({items,selected,set}:{items:string[],selected:string,set:(x:string)=>void}){return <div className="tabs">{items.map(x=><button key={x} className={selected===x?'selected':''} onClick={()=>set(x)}>{x}</button>)}</div>}
function Primary({children,onClick,signal=false,disabled=false}:{children:React.ReactNode,onClick?:()=>void,signal?:boolean,disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className={'primary '+(signal?'lime':'')}>{children}</button>}
function Notice({children}:{children:React.ReactNode}){return <p className="note"><ShieldCheck/>{children}</p>}

function Today({open}:Props){return <><div className="today-head"><b>FRIDAY · 4 SEP</b><div><Search/><Bell/></div></div><main className="content"><section className="summary"><div className="summary-head"><span>Orders today</span><b>LIVE</b></div><strong className="big">42</strong><div className="metrics"><button onClick={()=>open('V-12')}><b>18</b><span>Ready</span></button><button onClick={()=>open('V-16')}><b>16</b><span>Ongoing</span></button><button onClick={()=>open('V-12')}><b>8</b><span>Done</span></button></div></section><section><Section title="Need attention" action={()=>open('V-12')}/><button className="attention" onClick={()=>open('V-13')}><span>2</span><div><b>Orders need action</b><small>1 unassigned · 1 delayed</small></div><ChevronRight/></button></section><section><Section title="Recent deliveries" action={()=>open('V-19')}/><div className="list">{deliveries.map(([z,r,c,s])=><Row key={z} title={String(z)} sub={`${r} · ${c} deliveries`} status={String(s)} onClick={()=>open('V-19')}/>)}</div></section></main></>}
function Orders({open}:Props){const [filter,setFilter]=useState('All'),[q,setQ]=useState('');const shown=useMemo(()=>orders.filter(o=>(filter==='All'||o.status===filter.toUpperCase())&&(o.id+o.place).toLowerCase().includes(q.toLowerCase())),[filter,q]);return <main className="content page"><div className="title-row"><div><span className="eyebrow">TODAY</span><h2>Orders</h2></div><button className="add" onClick={()=>open('V-14')}><Plus/> New</button></div><label className="search"><Search/><input placeholder="Search orders" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')}><X/></button>}</label><Tabs items={['All','Ready','Ongoing','Done']} selected={filter} set={setFilter}/><div className="list">{shown.map(o=><Row key={o.id} title={o.id} sub={`${o.place} · ${o.items} items`} status={o.status} onClick={()=>open('V-13')}/>)}</div></main>}
function OrderDetail({open}:Props){return <main className="content detail"><div className="detail-hero"><span>READY</span><h2>#CF-1048</h2><p>Taman Melati · 3 items</p></div><Info rows={[["Customer","Nur Aisyah"],["Phone","+60 12 345 6789"],["Delivery window","2:00 PM – 4:00 PM"],["Zone","Zone North"],["Assigned rider","Not assigned"]]}/><Section title="Order items"/><div className="line-items"><div><span>2 × Nasi Lemak Ayam</span><b>RM24.00</b></div><div><span>1 × Iced Lemon Tea</span><b>RM6.50</b></div></div><div className="button-stack"><Primary onClick={()=>open('V-17')}>Prepare delivery</Primary><button className="secondary" onClick={()=>open('V-15')}>Edit order</button></div></main>}
function Zones({open}:Props){const [tab,setTab]=useState('Ready');const all=[['Zone North','12 orders · 2 riders','Ready'],['Zone South','8 orders · 2 riders','Ready'],['Zone Central','9 orders · 1 rider','Ongoing'],['Zone East','6 orders · 1 rider','Completed']];return <main className="content page"><span className="eyebrow">DELIVERY WORKSPACE</span><h2>Zones</h2><Tabs items={['Ready','Ongoing','Completed']} selected={tab} set={setTab}/><div className="list">{all.filter(x=>x[2]===tab).map(x=><Row key={x[0]} title={x[0]} sub={x[1]} status={x[2].toUpperCase()} onClick={()=>open(tab==='Ongoing'?'V-19':'V-17')}/>)}</div></main>}
function ZonePlan({open}:Props){return <main className="content detail"><div className="detail-hero"><span>READY TO PLAN</span><h2>Zone North</h2><p>12 orders · 2 riders</p></div><Info rows={[["Coverage","Within service area"],["Unassigned","0 orders"],["Conflicts","None"],["Rider capacity","Within limits"]]}/><Section title="Suggested runs"/><div className="run"><div><span>RUN 01</span><h3>Amir</h3><p>Motorcycle · 7 deliveries</p></div><Status>READY</Status></div><div className="run"><div><span>RUN 02</span><h3>Hafiz</h3><p>Car · 5 deliveries</p></div><Status>READY</Status></div><Primary onClick={()=>open('V-18')}>Review Plan</Primary><Notice>Suggested plan uses local prototype data. It does not claim live optimization.</Notice></main>}
function Dispatch({open}:Props){const [done,setDone]=useState(false);return <main className="content detail"><div className="review-band"><Check/><div><b>Plan checks complete</b><span>2 runs · 12 deliveries · no conflicts</span></div></div><Section title="Dispatch summary"/><Info rows={[["Zone","Zone North"],["Riders","Amir, Hafiz"],["Runs","2"],["Stops","12"]]}/><div className="route-strip"><span>Vendor</span><i/><span>12 stops</span><i/><span>Riders</span></div><Primary signal onClick={()=>setDone(true)}>{done?'Preview dispatch acknowledged':'Dispatch'}</Primary>{done&&<div className="inline-success"><Check/> Local prototype state only — nothing was dispatched.</div>}<button className="secondary full" onClick={()=>open('V-17')}>Back to plan</button></main>}
function Run(){return <main className="content detail"><div className="detail-hero"><span>ON ROUTE</span><h2>RUN 01</h2><p>Amir · Motorcycle · 7 deliveries</p></div><div className="progress"><i style={{width:'46%'}}/></div><p className="progress-label">3 of 7 stops completed</p><div className="timeline"><div className="done"><Check/><span><b>#CF-1039</b><small>Taman Melati · Delivered</small></span></div><div className="active"><Bike/><span><b>#CF-1041</b><small>Setapak · On route</small></span></div><div><span>3</span><span><b>#CF-1048</b><small>Wangsa Maju · Next</small></span></div></div><Notice>No live GPS or fabricated ETA is shown.</Notice></main>}
function Riders({open}:Props){return <main className="content page"><div className="title-row"><div><span className="eyebrow">WORKFORCE</span><h2>Riders</h2></div><button className="add" onClick={()=>open('V-22')}><Plus/> Invite</button></div><div className="list">{riders.map(([n,v,s])=><Row key={n} title={n} sub={`${v} · ${s==='On delivery'?'RUN 01':'No active run'}`} status={s} onClick={()=>open('V-21')}/>)}</div></main>}
function RiderDetail(){return <main className="content detail"><div className="identity"><span>A</span><div><h2>Amir</h2><p>Motorcycle</p></div><Status>On delivery</Status></div><Info rows={[["Current run","RUN 01 · Zone North"],["Deliveries today","7"],["Active orders","3"],["Maximum active orders","3"],["Invitation status","Accepted"]]}/><Notice>No live position or workforce HR data is fabricated.</Notice></main>}

const navMap:Record<string,[string,string,string,typeof Package][]>={
 'V-23':[['Sarah Lim','Owner · Active','V-24',UserRound],['Daniel Wong','Operator · Active','V-24',UserRound],['Pending invitation','operator@business.my','V-25',Clock3]],
 'V-26':[['Coverage','10 km radius · Kuala Lumpur','V-27',Map],['Zone configuration','4 reusable zones','V-28',Grid2X2]],
 'V-28':[['Zone North','Enabled · Priority 1','V-30',Grid2X2],['Zone South','Enabled · Priority 2','V-30',Grid2X2],['Zone Central','Enabled · Priority 3','V-30',Grid2X2],['Create zone','Add a coverage grouping','V-29',Plus]],
 'V-31':[['Storefront Preview','Customer-facing preview','V-32',Eye],['Appearance / Branding','Approved presentation controls','V-33',Sun],['Products','12 active · 2 hidden','V-34',Package]],
 'V-37':[['Business Information','Kopi Mak Long','V-38',Building2],['Business Address','Taman Melati, Kuala Lumpur','V-39',Map],['Business Hours','Open today · 9 AM–7 PM','V-40',Clock3],['Delivery Settings','Reconciliation hold','V-41',Settings]],
 'V-46':[['Notifications','Operational preferences','V-47',Bell],['Language','English','V-48',CircleHelp],['Appearance','System','V-49',Sun],['Privacy Policy','Information handling','V-58',ShieldCheck],['Terms of Service','Cefflo usage terms','V-59',Package],['About Cefflo','Version 0.9 prototype','V-60',CircleHelp]],
};
function ListScreen({s,open}:{s:Scene}&Props){const rows=navMap[s.id]||[];if(s.id==='V-34')return <Products open={open}/>;return <main className="content page"><span className="eyebrow">{s.group}</span><h2>{s.title}</h2><p className="intro">{s.subtitle}</p>{s.id==='V-23'&&<button className="add standalone" onClick={()=>open('V-25')}><Plus/> Invite member</button>}<div className="list">{rows.map(([a,b,id,Icon])=><Row key={a} title={a} sub={b} Icon={Icon} onClick={()=>open(id)}/>)}</div></main>}
function Products({open}:Props){const [tab,setTab]=useState('Active');return <main className="content page"><div className="title-row"><div><span className="eyebrow">STOREFRONT</span><h2>Products</h2></div><button className="add" onClick={()=>open('V-36')}><Plus/> Add</button></div><Tabs items={['Active','Hidden']} selected={tab} set={setTab}/>{['Food','Drinks','Dessert'].map((cat,i)=><section className="product-group" key={cat}><Section title={cat}/>{tab==='Active'?<><Row title={['Nasi Lemak Ayam','Iced Matcha Latte','Pandan Cloud Cake'][i]} sub={['Coconut rice · chicken','Ceremonial matcha · milk','Pandan · coconut cream'][i]} status="ACTIVE" onClick={()=>open('V-35')}/><Row title={['Mee Kari Special','Iced Lemon Tea','Strawberry Donut'][i]} sub="Available on storefront" status="ACTIVE" onClick={()=>open('V-35')}/></>:<Row title={`${cat} sample`} sub="Hidden from storefront" status="HIDDEN" onClick={()=>open('V-35')}/>}</section>)}</main>}

const formConfig:Record<string,{fields:[string,string,string][],action:string}>={
'V-07':{fields:[['Business name','Kopi Mak Long','text'],['Business phone','+60 12 345 6789','tel'],['Business description','Local favourites, delivered fresh.','textarea']],action:'Continue'},
'V-08':{fields:[['Address','Jalan Taman Melati, Kuala Lumpur','text'],['Unit / floor','','text'],['Postcode','53100','text']],action:'Confirm location'},
'V-09':{fields:[['Operating centre','Taman Melati, Kuala Lumpur','text'],['Delivery radius','10 km','text']],action:'Save service area'},
'V-14':{fields:[['Customer name','Nur Aisyah','text'],['Phone number','+60 12 345 6789','tel'],['Delivery address','Taman Melati, Kuala Lumpur','textarea'],['Order note','Leave at guardhouse','textarea']],action:'Create order preview'},
'V-15':{fields:[['Customer name','Nur Aisyah','text'],['Phone number','+60 12 345 6789','tel'],['Delivery address','Taman Melati, Kuala Lumpur','textarea'],['Delivery note','Call on arrival','textarea']],action:'Save changes'},
'V-22':{fields:[['Rider name','Iskandar Rahman','text'],['Mobile number','+60 11 222 3344','tel'],['Vehicle','Motorcycle','select']],action:'Create invitation preview'},
'V-25':{fields:[['Full name','Nadia Rahman','text'],['Email','nadia@business.my','email'],['Role','Operator','select']],action:'Create invitation preview'},
'V-27':{fields:[['Operating centre','Taman Melati, Kuala Lumpur','text'],['Delivery radius','10 km','text']],action:'Save coverage preview'},
'V-29':{fields:[['Zone name','Zone West','text'],['Description','Western delivery grouping','textarea']],action:'Create zone preview'},
'V-30':{fields:[['Zone name','Zone North','text'],['Description','Northern service area grouping','textarea'],['Status','Enabled','select']],action:'Save zone preview'},
'V-38':{fields:[['Business name','Kopi Mak Long','text'],['Business phone','+60 12 345 6789','tel'],['Description','Local favourites, delivered fresh.','textarea']],action:'Save business info'},
'V-39':{fields:[['Address','Jalan Taman Melati, Kuala Lumpur','textarea'],['Postcode','53100','text']],action:'Save address preview'},
'V-43':{fields:[['Full name','Nur Farah','text'],['Email','farah@kopimaklong.my','email'],['Phone','+60 12 345 6789','tel']],action:'Save profile preview'},
'V-45':{fields:[['Current password','','password'],['New password','','password'],['Confirm new password','','password']],action:'Validate password preview'},
'V-57':{fields:[['Subject','Help with delivery planning','text'],['Message','Describe what happened...','textarea']],action:'Prepare request'},
};
function FormScreen({s,open}:{s:Scene}&Props){const cfg=formConfig[s.id]||formConfig['V-38'];const [saved,setSaved]=useState(false);return <main className="content page"><span className="eyebrow">{s.group}</span><h2>{s.title}</h2><p className="intro">{s.subtitle}</p><div className="form">{cfg.fields.map(([label,value,type])=><label key={label}><span>{label}</span>{type==='textarea'?<textarea defaultValue={value}/>:type==='select'?<select defaultValue={value}><option>{value}</option><option>{value==='Enabled'?'Disabled':'Car'}</option></select>:<input type={type} defaultValue={value}/>}</label>)}</div><Primary onClick={()=>setSaved(true)}>{cfg.action}</Primary>{saved&&<div className="inline-success"><Check/> Saved in this local prototype only.</div>}{s.next&&<button className="secondary full" onClick={()=>open(s.next!)}>Continue to {scene(s.next).title}</button>}</main>}
function Product({s,open}:{s:Scene}&Props){const [active,setActive]=useState(true),[saved,setSaved]=useState(false);return <main className="content page"><div className="photo-placeholder"><Package/><span>Product media preview</span></div><div className="form"><label><span>Product name</span><input defaultValue={s.id==='V-35'?'Nasi Lemak Ayam':''} placeholder="Enter product name"/></label><label><span>Category</span><select defaultValue="Food"><option>Food</option><option>Drinks</option><option>Dessert</option></select></label><label><span>Description</span><textarea defaultValue={s.id==='V-35'?'Coconut rice, sambal and crispy chicken.':''}/></label><label><span>Display price</span><input defaultValue={s.id==='V-35'?'12.00':''} inputMode="decimal"/></label></div><button className="toggle-row" onClick={()=>setActive(!active)}><span><b>Visible on storefront</b><small>{active?'Active':'Hidden'}</small></span><i className={active?'on':''}><em/></i></button><Primary onClick={()=>setSaved(true)}>Save Product</Primary>{saved&&<div className="inline-success"><Check/> Product updated in local prototype.</div>}<button className="secondary full" onClick={()=>open('V-34')}>Back to Products</button></main>}
function SettingsScreen({s,open}:{s:Scene}&Props){const [choice,setChoice]=useState(s.id==='V-49'?'System':s.id==='V-48'?'English':'Enabled');const options=s.id==='V-49'?['Light','Dark','System']:s.id==='V-48'?['English','Bahasa Melayu']:s.id==='V-47'?['Enabled','Muted']:['Owner','Operator'];if(s.id==='V-24')return <main className="content detail"><div className="identity"><span>S</span><div><h2>Sarah Lim</h2><p>Owner · Active</p></div><Status>ACTIVE</Status></div><Info rows={[["Email","sarah@business.my"],["Role","Owner"],["Joined","12 Aug 2026"],["Access","Full business access"]]}/></main>;
 if(s.id==='V-33')return <main className="content page"><span className="eyebrow">APPROVED CONTROLS</span><h2>Appearance / Branding</h2><p className="intro">Choose a restrained storefront presentation.</p><div className="theme-grid">{['Clean','Warm','Fresh','Midnight'].map(x=><button key={x} className={choice===x?'selected':''} onClick={()=>setChoice(x)}><i className={x.toLowerCase()}/><b>{x}</b></button>)}</div><Primary onClick={()=>open('V-32')}>View storefront preview</Primary></main>;
 if(s.id==='V-40')return <main className="content page"><span className="eyebrow">BUSINESS PROFILE</span><h2>Business Hours</h2>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=><button className="hours" key={d}><b>{d}</b><span>{i===6?'Closed':'9:00 AM – 7:00 PM'}</span><ChevronRight/></button>)}</main>;
 return <main className="content page"><span className="eyebrow">{s.group}</span><h2>{s.title}</h2><p className="intro">{s.subtitle}</p><div className="choice-list">{options.map(x=><button key={x} className={choice===x?'selected':''} onClick={()=>setChoice(x)}><span>{x}</span>{choice===x&&<Check/>}</button>)}</div>{s.id==='V-42'&&<Primary onClick={()=>open('V-43')}>Edit Profile</Primary>}{s.id==='V-44'&&<Primary onClick={()=>open('V-45')}>Change Password</Primary>}{s.id==='V-60'&&<Info rows={[["Version","0.9 prototype"],["Build","60-scene preview"],["Environment","Local data only"]]}/>}</main>}
function Storefront(){return <main className="storefront"><div className="store-brand"><span>KM</span><div><b>Kopi Mak Long</b><small>Direct order page · Preview only</small></div></div><div className="store-product"><div className="food-shape"><span/><i/></div><span className="eyebrow">TODAY’S SELECTION</span><h2>Nasi Lemak Ayam</h2><p>Coconut rice, sambal and crispy chicken.</p><b>RM12.00</b></div><div className="store-rail"><button className="selected">Food</button><button>Drinks</button><button>Dessert</button></div><Notice>Customer ordering is not connected in this Vendor prototype.</Notice></main>}
function Setup({s,open}:{s:Scene}&Props){if(s.id==='V-01')return <main className="entry"><div className="mark"><Zap/></div><h1>Cefflo Vendor</h1><p>Local delivery operations, clearly managed.</p><Primary onClick={()=>open('V-02')}>Open prototype</Primary></main>;return <main className="entry setup"><span className="setup-step">{s.id==='V-06'?'01':s.id==='V-10'?'05':'SETUP'} / 05</span><div className="mark small"><Check/></div><h1>{s.title}</h1><p>{s.subtitle}</p><Primary signal={s.id==='V-10'} onClick={()=>open(s.next||'V-11')}>{s.id==='V-10'?'Enter Today':'Continue'}</Primary></main>}
function Auth({s,open}:{s:Scene}&Props){const [sent,setSent]=useState(false);return <main className="auth"><div className="auth-brand"><div className="mark small"><Zap/></div><span>CEFFLO VENDOR</span></div><h1>{s.title}</h1><p>{s.subtitle}</p><div className="form"><label><span>Email</span><input type="email" defaultValue={s.id==='V-02'?'vendor@cefflo.test':''}/></label>{s.id!=='V-04'&&<label><span>{s.id==='V-05'?'New password':'Password'}</span><input type="password" defaultValue="Cefflo123!"/></label>}</div><Primary onClick={()=>{setSent(true);if(s.id==='V-02')setTimeout(()=>open('V-11'),250)}}>{s.id==='V-02'?'Sign In':s.id==='V-03'?'Create Account':s.id==='V-04'?'Send recovery link':'Reset password'}</Primary>{sent&&s.id!=='V-02'&&<div className="inline-success"><Check/> Prototype action acknowledged.</div>}<div className="auth-links">{s.id==='V-02'&&<><button onClick={()=>open('V-04')}>Forgot password?</button><button onClick={()=>open('V-03')}>Create account</button></>}{s.id!=='V-02'&&<button onClick={()=>open('V-02')}>Back to sign in</button>}</div><Notice>No authentication request is sent. This is a local prototype.</Notice></main>}
function Hold({s}:{s:Scene}){return <main className="content page"><div className="hold"><LockKeyhole/><span>FOUNDER HOLD</span><h2>{s.title}</h2><p>{s.subtitle}</p></div><Info rows={[["Status","Not implementation-ready"],["Backend","Not connected"],["Payment claim","None"],["Production action","Disabled"]]}/><Notice>This screen preserves the inventory boundary without inventing product or payment decisions.</Notice></main>}
function Support({s,open}:{s:Scene}&Props){if(s.id==='V-55')return <main className="content page"><span className="eyebrow">SUPPORT</span><h2>How can we help?</h2><div className="support-card"><LifeBuoy/><div><b>Operational support</b><span>Guidance for orders, zones and riders.</span></div></div><Row title="Help Centre" sub="Browse common operational questions" onClick={()=>open('V-56')}/><Row title="Contact Support" sub="Prepare a support request" onClick={()=>open('V-57')}/></main>;return <main className="content page"><span className="eyebrow">HELP CENTRE</span><h2>Common questions</h2>{['How do I prepare a delivery plan?','Why is an order in Need Attention?','How do rider invitations work?','What happens after dispatch?'].map(x=><button className="faq" key={x}><span>{x}</span><ChevronDown/></button>)}</main>}
function Legal({s}:{s:Scene}){return <main className="content legal"><span className="eyebrow">LEGAL</span><h2>{s.title}</h2><p>Last updated · 4 September 2026</p>{['Purpose and scope','Information we handle','How Cefflo operates','Your responsibilities','Support and contact'].map((h,i)=><section key={h}><h3>{h}</h3><p>{i===0?'This prototype presents the structure of the future Cefflo Vendor experience.':'Final legal copy remains subject to the canonical approved policy. This preview does not replace published legal terms.'}</p></section>)}</main>}
function SceneIndex({open,close}:{open:(id:string)=>void,close:()=>void}){const [q,setQ]=useState('');const filtered=scenes.filter(s=>(s.id+s.title+s.group).toLowerCase().includes(q.toLowerCase()));return <div className="index-overlay"><div className="index-sheet"><div className="index-head"><div><span>CEFFLO VENDOR</span><h2>60-scene navigator</h2></div><button className="icon" onClick={close}><X/></button></div><label className="search"><Search/><input placeholder="Find a scene" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="index-list">{filtered.map((s,i)=>{const show=i===0||filtered[i-1].group!==s.group;return <div key={s.id}>{show&&<h3>{s.group}</h3>}<button onClick={()=>open(s.id)}><span>{s.id}</span><b>{s.title}</b>{s.hold&&<em>HOLD</em>}<ChevronRight/></button></div>})}</div></div></div>}

function Screen({s,open}:{s:Scene}&Props){switch(s.kind){case'entry':return <Setup s={s} open={open}/>;case'auth':return <Auth s={s} open={open}/>;case'setup':return <Setup s={s} open={open}/>;case'today':return <Today open={open}/>;case'orders':return <Orders open={open}/>;case'order-detail':return <OrderDetail open={open}/>;case'zones':return <Zones open={open}/>;case'zone-detail':return <ZonePlan open={open}/>;case'dispatch':return <Dispatch open={open}/>;case'run':return <Run/>;case'riders':return <Riders open={open}/>;case'rider-detail':return <RiderDetail/>;case'list':return <ListScreen s={s} open={open}/>;case'form':return <FormScreen s={s} open={open}/>;case'product':return <Product s={s} open={open}/>;case'settings':return <SettingsScreen s={s} open={open}/>;case'storefront':return <Storefront/>;case'products':return <Products open={open}/>;case'hold':return <Hold s={s}/>;case'support':return <Support s={s} open={open}/>;case'legal':return <Legal s={s}/>}}
const roots=['V-11','V-12','V-16','V-20'];const nav=[['V-11','Today',Zap],['V-12','Orders',Package],['V-16','Zones',Grid2X2],['V-20','Riders',Bike],['MENU','Menu',MenuIcon]] as const;
export default function Home(){const [current,setCurrent]=useState('V-11'),[history,setHistory]=useState<string[]>([]),[index,setIndex]=useState(false);const s=scene(current);const open=(id:string)=>{setHistory(h=>[...h,current]);setCurrent(id);setIndex(false);document.querySelector('.body')?.scrollTo(0,0)};const back=()=>{const prev=history.at(-1)||'V-11';setCurrent(prev);setHistory(h=>h.slice(0,-1))};const openMenu=()=>open('V-46');const showNav=roots.includes(current)||current==='V-46';return <div className="stage"><div className="shell"><div className="body">{!['entry','auth','setup','today'].includes(s.kind)&&<Header s={s} back={showNav?undefined:back} onIndex={()=>setIndex(true)}/>}<Screen s={s} open={open}/></div>{showNav&&<nav>{nav.map(([id,label,Icon])=><button key={id} className={(id===current||(id==='MENU'&&current==='V-46'))?'active':''} onClick={()=>id==='MENU'?openMenu():open(id)}><Icon/><span>{label}</span></button>)}</nav>}{index&&<SceneIndex open={open} close={()=>setIndex(false)}/>}</div><button className="prototype" onClick={()=>setIndex(true)}>60-SCENE PROTOTYPE · LOCAL DATA ONLY</button></div>}
