'use client';
import {useMemo,useState} from 'react';
import {ArrowLeft,Bell,Bike,Building2,ChevronRight,CircleHelp,Grid2X2,KeyRound,LogOut,Map,Menu as MenuIcon,Package,Search,Settings,Store,UserRound,UsersRound,X,Zap} from 'lucide-react';
type Tab='today'|'orders'|'zones'|'riders'|'menu'; type View={name:string,id?:string};
const orders=[['#CF-1048','Taman Melati',3,'READY'],['#CF-1047','Setapak',2,'READY'],['#CF-1046','Wangsa Maju',4,'ONGOING'],['#CF-1045','Gombak',1,'DONE'],['#CF-1044','Sentul',2,'DONE']].map(([id,place,items,status])=>({id:String(id),place:String(place),items:Number(items),status:String(status)}));
const deliveries=[['north','Zone North','Amir',7,'ON ROUTE'],['central','Zone Central','Hafiz',5,'COMPLETED'],['south','Zone South','Aiman',4,'READY'],['east','Zone East','Farid',6,'COMPLETED']].map(([id,name,rider,count,status])=>({id:String(id),name:String(name),rider:String(rider),count:Number(count),status:String(status)}));
const zones=[['north','Zone North',12,2,'Ready'],['south','Zone South',8,2,'Ready'],['central','Zone Central',9,1,'Ongoing'],['east','Zone East',6,1,'Completed']].map(([id,name,orders,riders,status])=>({id:String(id),name:String(name),orders:Number(orders),riders:Number(riders),status:String(status)}));
const riders=[['amir','Amir','Motorcycle','On delivery','RUN 01 · Zone North',7,'3 active orders'],['hafiz','Hafiz','Car','Available','No active run',5,'5 active orders'],['aiman','Aiman','Motorcycle','Available','No active run',4,'3 active orders'],['farid','Farid','Van','Offline','No active run',6,'8 active orders']].map(([id,name,vehicle,status,run,count,capacity])=>({id:String(id),name:String(name),vehicle:String(vehicle),status:String(status),run:String(run),count:Number(count),capacity:String(capacity)}));
const groups=[{title:'BUSINESS',items:[['Team',UsersRound],['Service Area',Map],['Storefront / Appearance',Store],['Business Profile',Building2]]},{title:'ACCOUNT',items:[['Profile',UserRound],['Security',KeyRound],['Settings',Settings]]},{title:'SUPPORT',items:[['Help & Support',CircleHelp],['Log Out',LogOut]]}];
function Status({text}:{text:string}){return <span className={'status '+(['READY','ON ROUTE','ONGOING','Ready','On delivery','Available'].includes(text)?'live':'')}>{text}</span>}
function Header({title,back,tools=true}:{title:string,back?:()=>void,tools?:boolean}){return <header><div className="head-title">{back&&<button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button>}<h1>{title}</h1></div>{tools&&<div className="head-tools"><button className="icon"><Search/></button><button className="icon bell"><Bell/><i/></button></div>}</header>}
function Section({title,action}:{title:string,action?:()=>void}){return <div className="section-title"><h2>{title}</h2>{action&&<button onClick={action}>See All <ChevronRight/></button>}</div>}
function Row({title,sub,status,onClick,Icon}:{title:string,sub?:string,status?:string,onClick?:()=>void,Icon?:typeof Package}){return <button className="row" onClick={onClick}>{Icon&&<span className="row-icon"><Icon/></span>}<span className="row-copy"><b>{title}</b>{sub&&<small>{sub}</small>}</span>{status&&<Status text={status}/>}<ChevronRight className="chev"/></button>}
function Detail({title,back,children}:{title:string,back:()=>void,children:React.ReactNode}){return <><Header title={title} back={back} tools={false}/><main className="content detail">{children}</main></>}
function Info({rows}:{rows:[string,string][]}){return <div className="info">{rows.map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}
export default function Home(){
 const [tab,setTab]=useState<Tab>('today'),[view,setView]=useState<View>({name:'root'}),[filter,setFilter]=useState('All'),[zoneFilter,setZoneFilter]=useState('Ready'),[query,setQuery]=useState(''),[reviewed,setReviewed]=useState(false),[dispatched,setDispatched]=useState(false);
 const go=(name:string,id?:string)=>setView({name,id}); const home=(t:Tab)=>{setTab(t);go('root')};
 const shown=useMemo(()=>orders.filter(o=>(filter==='All'||o.status===filter.toUpperCase())&&(o.id+o.place).toLowerCase().includes(query.toLowerCase())),[filter,query]); let screen:React.ReactNode;
 if(view.name==='attention')screen=<Detail title="Need attention" back={()=>go('root')}><div className="list"><Row title="Order #CF-1047" sub="No rider assigned · Zone South" status="ACTION" onClick={()=>go('order','#CF-1047')}/><Row title="Order #CF-1042" sub="12 min behind planned window" status="DELAYED" onClick={()=>go('order','#CF-1042')}/></div></Detail>;
 else if(view.name==='recent')screen=<Detail title="Recent deliveries" back={()=>go('root')}><div className="list">{deliveries.map(d=><Row key={d.id} title={d.name} sub={`${d.rider} · ${d.count} deliveries`} status={d.status} onClick={()=>go('delivery',d.id)}/>)}</div></Detail>;
 else if(view.name==='delivery'){const d=deliveries.find(x=>x.id===view.id)||deliveries[0];screen=<Detail title="Delivery detail" back={()=>go('recent')}><div className="detail-hero"><span>{d.status}</span><h2>{d.name}</h2><p>Today’s verified delivery run.</p></div><Info rows={[["Rider",d.rider],["Deliveries",String(d.count)],["Vehicle",d.rider==='Farid'?'Van':'Motorcycle'],["Status",d.status]]}/><p className="note">Location and ETA are not shown in this prototype.</p></Detail>}
 else if(view.name==='order'){const o=orders.find(x=>x.id===view.id)||orders[0];screen=<Detail title="Order detail" back={()=>home('orders')}><div className="detail-hero"><span>{o.status}</span><h2>{o.id}</h2><p>{o.place} · {o.items} items</p></div><Info rows={[["Customer","Nur Aisyah"],["Delivery area",o.place],["Items",`${o.items} items`],["Status",o.status],["Requested window","2:00 PM – 4:00 PM"]]}/><button className="primary">Review order</button></Detail>}
 else if(view.name==='zone'){const z=zones.find(x=>x.id===view.id)||zones[0];screen=<Detail title={z.name} back={()=>home('zones')}><div className="detail-hero"><span>DELIVERY PLAN</span><h2>{z.orders} orders</h2><p>{z.riders} assigned riders · {z.status}</p></div><div className="run"><div><span>RUN 01</span><h3>Amir</h3><p>Motorcycle · 7 deliveries</p></div><Status text={dispatched?'ON ROUTE':'READY'}/></div><Info rows={[["Plan status",dispatched?'Dispatched':reviewed?'Reviewed · Ready':'Suggested'],["Conflicts","None detected"],["Unassigned orders","0"]]}/>{!reviewed?<button className="primary" onClick={()=>setReviewed(true)}>Review Plan</button>:<button className="primary lime" onClick={()=>setDispatched(true)}>{dispatched?'Dispatched for this preview':'Dispatch'}</button>}<p className="note">Suggested plan uses local preview data. No live dispatch occurs.</p></Detail>}
 else if(view.name==='rider'){const r=riders.find(x=>x.id===view.id)||riders[0];screen=<Detail title="Rider detail" back={()=>home('riders')}><div className="identity"><span>{r.name[0]}</span><div><h2>{r.name}</h2><p>{r.vehicle}</p></div><Status text={r.status}/></div><Info rows={[["Current run",r.run],["Deliveries today",String(r.count)],["Order capacity",r.capacity],["Operational status",r.status]]}/><p className="note">No live GPS position is shown.</p></Detail>}
 else if(view.name==='menu-detail')screen=<Detail title={view.id||'Settings'} back={()=>home('menu')}><div className="empty"><Settings/><h2>{view.id}</h2><p>This destination is structurally available without claiming connected settings.</p></div></Detail>;
 else if(tab==='today')screen=<><Header title="FRIDAY · 4 SEP"/><main className="content"><section className="summary"><div className="summary-head"><span>Orders today</span><b>LIVE</b></div><strong className="big">42</strong><div className="metrics"><div><b>18</b><span>Ready</span></div><div><b>16</b><span>Ongoing</span></div><div><b>8</b><span>Done</span></div></div></section><section><Section title="Need attention" action={()=>go('attention')}/><button className="attention" onClick={()=>go('attention')}><span>2</span><div><b>Orders need action</b><small>1 unassigned · 1 delayed</small></div><ChevronRight/></button></section><section><Section title="Recent deliveries" action={()=>go('recent')}/><div className="list">{deliveries.slice(0,3).map(d=><Row key={d.id} title={d.name} sub={`${d.rider} · ${d.count} deliveries`} status={d.status} onClick={()=>go('delivery',d.id)}/>)}</div></section></main></>;
 else if(tab==='orders')screen=<><Header title="Orders"/><main className="content"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders"/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</label><div className="tabs">{['All','Ready','Ongoing','Done'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="list">{shown.map(o=><Row key={o.id} title={o.id} sub={`${o.place} · ${o.items} items`} status={o.status} onClick={()=>go('order',o.id)}/>)}{!shown.length&&<p className="none">No matching orders.</p>}</div></main></>;
 else if(tab==='zones')screen=<><Header title="Zones"/><main className="content"><div className="tabs wide">{['Ready','Ongoing','Completed'].map(x=><button className={zoneFilter===x?'selected':''} onClick={()=>setZoneFilter(x)} key={x}>{x}</button>)}</div><p className="intro">Today’s operational delivery groups.</p><div className="list">{zones.filter(z=>z.status===zoneFilter).map(z=><Row key={z.id} title={z.name} sub={`${z.orders} orders · ${z.riders} riders`} status={z.status.toUpperCase()} onClick={()=>{setReviewed(false);setDispatched(false);go('zone',z.id)}}/>)}</div></main></>;
 else if(tab==='riders')screen=<><Header title="Riders"/><main className="content"><p className="intro">Availability and today’s delivery work.</p><div className="list">{riders.map(r=><Row key={r.id} title={r.name} sub={`${r.vehicle} · ${r.run}`} status={r.status} onClick={()=>go('rider',r.id)}/>)}</div></main></>;
 else screen=<><Header title="Menu"/><main className="content menu-page">{groups.map(g=><section key={g.title}><h2 className="group">{g.title}</h2><div className="list">{g.items.map(([label,Icon])=><Row key={label as string} title={label as string} Icon={Icon as typeof Package} onClick={()=>go('menu-detail',label as string)}/>)}</div></section>)}</main></>;
 const nav=[['today','Today',Zap],['orders','Orders',Package],['zones','Zones',Grid2X2],['riders','Riders',Bike],['menu','Menu',MenuIcon]] as const;
 return <div className="stage"><div className="shell"><div className="body">{screen}</div>{view.name==='root'&&<nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>home(id)}><Icon/><span>{label}</span></button>)}</nav>}</div><div className="prototype">INTERACTIVE PROTOTYPE · LOCAL DATA ONLY</div></div>;
}
