export type SceneKind='entry'|'auth'|'setup'|'today'|'orders'|'order-detail'|'form'|'zones'|'zone-detail'|'dispatch'|'run'|'riders'|'rider-detail'|'list'|'settings'|'storefront'|'products'|'product'|'hold'|'support'|'legal';
export type Scene={id:string;title:string;group:string;kind:SceneKind;subtitle:string;next?:string;hold?:boolean};
export const scenes:Scene[]=[
['V-01','Splash','ENTRY','entry','Secure workspace initialization.','V-02'],
['V-02','Sign In','AUTHENTICATION','auth','Access your business operations.','V-06'],
['V-03','Create Account','AUTHENTICATION','auth','Register a new Vendor account.','V-06'],
['V-04','Forgot Password','AUTHENTICATION','auth','Request a secure recovery link.','V-05'],
['V-05','Reset Password','AUTHENTICATION','auth','Choose a new account password.','V-02'],
['V-06','Welcome to Cefflo','ONBOARDING','setup','Set up the essentials for your delivery operation.','V-07'],
['V-07','Business Information','ONBOARDING','form','Add the identity customers and riders will see.','V-08'],
['V-08','Business Location','ONBOARDING','form','Set the real operating address for this business.','V-09'],
['V-09','Service Area Setup','ONBOARDING','form','Define the first delivery coverage area.','V-10'],
['V-10','Setup Complete','ONBOARDING','setup','Your operational workspace is ready.','V-11'],
['V-11','Today','OPERATIONS','today','The current delivery day at a glance.'],
['V-12','Orders','ORDERS','orders','Review and manage today’s order flow.'],
['V-13','Order Detail','ORDERS','order-detail','Canonical details for order #CF-1048.'],
['V-14','New Order','ORDERS','form','Create a delivery order.','V-13'],
['V-15','Edit Order','ORDERS','form','Update permitted delivery details.','V-13'],
['V-16','Zones','DELIVERY OPERATIONS','zones','Today’s operational delivery groups.'],
['V-17','Zone Detail / Delivery Plan','DELIVERY OPERATIONS','zone-detail','Prepare Zone North for dispatch.','V-18'],
['V-18','Review & Dispatch','DELIVERY OPERATIONS','dispatch','Review the delivery plan before dispatch.','V-19'],
['V-19','Active Run','DELIVERY OPERATIONS','run','Monitor RUN 01 and its stops.'],
['V-20','Riders','RIDERS','riders','Availability and today’s delivery work.'],
['V-21','Rider Detail','RIDERS','rider-detail','Amir’s current operational context.'],
['V-22','Invite Rider','RIDERS','form','Send a trusted rider invitation.','V-20'],
['V-23','Team','BUSINESS · TEAM','list','People with access to this business.'],
['V-24','Team Member Detail','BUSINESS · TEAM','settings','Role and access for Sarah Lim.'],
['V-25','Invite Team Member','BUSINESS · TEAM','form','Invite a trusted business team member.','V-23'],
['V-26','Service Area','BUSINESS · COVERAGE','list','Coverage configuration, separate from today’s Zones.'],
['V-27','Coverage Setup / Edit','BUSINESS · COVERAGE','form','Edit the business operating centre and radius.','V-26'],
['V-28','Zone Configuration','BUSINESS · COVERAGE','list','Manage reusable delivery zones.'],
['V-29','Create Zone','BUSINESS · COVERAGE','form','Create a zone within the service area.','V-28'],
['V-30','Edit Zone','BUSINESS · COVERAGE','form','Rename or change an existing zone.','V-28'],
['V-31','Storefront / Appearance','BUSINESS · STOREFRONT','list','Control approved customer-facing presentation.'],
['V-32','Storefront Preview','BUSINESS · STOREFRONT','storefront','Preview the direct customer order page.'],
['V-33','Appearance / Branding','BUSINESS · STOREFRONT','settings','Select approved storefront presentation.'],
['V-34','Products','BUSINESS · STOREFRONT','products','Manage the active customer-facing catalog.'],
['V-35','Edit Product','BUSINESS · STOREFRONT','product','Update Nasi Lemak Ayam.','V-34'],
['V-36','Add Product','BUSINESS · STOREFRONT','product','Add a new catalog product.','V-34'],
['V-37','Business Profile','BUSINESS PROFILE','list','Business identity and operating information.'],
['V-38','Business Information','BUSINESS PROFILE','form','Edit canonical business details.','V-37'],
['V-39','Business Address','BUSINESS PROFILE','form','Manage the business operating address.','V-37'],
['V-40','Business Hours','BUSINESS PROFILE','settings','Set customer-facing operating hours.'],
['V-41','Delivery Settings','BUSINESS PROFILE','hold','Responsibility must remain distinct from Service Area and Zones.',undefined,true],
['V-42','Profile','ACCOUNT · PROFILE','settings','Your personal account information.'],
['V-43','Edit Profile','ACCOUNT · PROFILE','form','Update permitted personal details.','V-42'],
['V-44','Security','ACCOUNT · SECURITY','settings','Password and account security.'],
['V-45','Change Password','ACCOUNT · SECURITY','form','Change the authenticated account password.','V-44'],
['V-46','Settings','ACCOUNT · SETTINGS','list','Application preferences and information.'],
['V-47','Notifications','ACCOUNT · SETTINGS','settings','Choose operational notification preferences.'],
['V-48','Language','ACCOUNT · SETTINGS','settings','Choose the app language.'],
['V-49','Appearance','ACCOUNT · SETTINGS','settings','Choose Light, Dark or System.'],
['V-50','Subscription / Plan','SUBSCRIPTION · HOLD','hold','Founder decision pending for Cefflo subscription architecture.',undefined,true],
['V-51','Choose / Change Plan','SUBSCRIPTION · HOLD','hold','Plan structure is not approved.',undefined,true],
['V-52','Subscription Checkout','SUBSCRIPTION · HOLD','hold','No payment provider or method has been approved.',undefined,true],
['V-53','Payment Result','SUBSCRIPTION · HOLD','hold','No transaction is simulated or claimed.',undefined,true],
['V-54','Subscription Details','SUBSCRIPTION · HOLD','hold','Renewal and billing contracts remain unresolved.',undefined,true],
['V-55','Help & Support','SUPPORT','support','Get help with Cefflo operations.'],
['V-56','Help Centre','SUPPORT','support','Browse practical Vendor guidance.'],
['V-57','Contact Support','SUPPORT','form','Prepare a support request.','V-55'],
['V-58','Privacy Policy','LEGAL / ABOUT','legal','How Cefflo handles information.'],
['V-59','Terms of Service','LEGAL / ABOUT','legal','Terms governing use of Cefflo.'],
['V-60','About Cefflo','LEGAL / ABOUT','settings','Version and application information.'],
].map(([id,title,group,kind,subtitle,next,hold])=>({id,title,group,kind,subtitle,next,hold})) as Scene[];
export const scene=(id:string)=>scenes.find(item=>item.id===id)??scenes[10];
