enum SceneKind {
  entry,
  auth,
  setup,
  today,
  orders,
  orderDetail,
  form,
  zones,
  zoneDetail,
  dispatch,
  run,
  riders,
  riderDetail,
  list,
  settings,
  storefront,
  products,
  product,
  hold,
  support,
  legal,
}

class Scene {
  const Scene(
    this.id,
    this.title,
    this.group,
    this.kind,
    this.subtitle, {
    this.next,
    this.hold = false,
  });
  final String id, title, group, subtitle;
  final SceneKind kind;
  final String? next;
  final bool hold;
}

const scenes = <Scene>[
  Scene(
    'V-01',
    'Splash',
    'ENTRY',
    SceneKind.entry,
    'Secure workspace initialization.',
    next: 'V-02',
  ),
  Scene(
    'V-02',
    'Sign In',
    'AUTHENTICATION',
    SceneKind.auth,
    'Access your business operations.',
    next: 'V-06',
  ),
  Scene(
    'V-03',
    'Create Account',
    'AUTHENTICATION',
    SceneKind.auth,
    'Register a new Vendor account.',
    next: 'V-06',
  ),
  Scene(
    'V-04',
    'Forgot Password',
    'AUTHENTICATION',
    SceneKind.auth,
    'Request a secure recovery link.',
    next: 'V-05',
  ),
  Scene(
    'V-05',
    'Reset Password',
    'AUTHENTICATION',
    SceneKind.auth,
    'Choose a new account password.',
    next: 'V-02',
  ),
  Scene(
    'V-06',
    'Welcome to Cefflo',
    'ONBOARDING',
    SceneKind.setup,
    'Set up the essentials for your operation.',
    next: 'V-07',
  ),
  Scene(
    'V-07',
    'Business Information',
    'ONBOARDING',
    SceneKind.form,
    'Add the identity customers and riders will see.',
    next: 'V-08',
  ),
  Scene(
    'V-08',
    'Business Location',
    'ONBOARDING',
    SceneKind.form,
    'Set the real operating address for this business.',
    next: 'V-09',
  ),
  Scene(
    'V-09',
    'Service Area Setup',
    'ONBOARDING',
    SceneKind.form,
    'Define the first delivery coverage area.',
    next: 'V-10',
  ),
  Scene(
    'V-10',
    'Setup Complete',
    'ONBOARDING',
    SceneKind.setup,
    'Your operational workspace is ready.',
    next: 'V-11',
  ),
  Scene(
    'V-11',
    'Today',
    'OPERATIONS',
    SceneKind.today,
    'The current delivery day at a glance.',
  ),
  Scene(
    'V-12',
    'Orders',
    'ORDERS',
    SceneKind.orders,
    'Review and manage today’s order flow.',
  ),
  Scene(
    'V-13',
    'Order Detail',
    'ORDERS',
    SceneKind.orderDetail,
    'Canonical details for order #CF-1048.',
  ),
  Scene(
    'V-14',
    'New Order',
    'ORDERS',
    SceneKind.form,
    'Create a delivery order.',
    next: 'V-13',
  ),
  Scene(
    'V-15',
    'Edit Order',
    'ORDERS',
    SceneKind.form,
    'Update permitted delivery details.',
    next: 'V-13',
  ),
  Scene(
    'V-16',
    'Zones',
    'DELIVERY OPERATIONS',
    SceneKind.zones,
    'Today’s operational delivery groups.',
  ),
  Scene(
    'V-17',
    'Zone Detail / Delivery Plan',
    'DELIVERY OPERATIONS',
    SceneKind.zoneDetail,
    'Prepare Zone North for dispatch.',
    next: 'V-18',
  ),
  Scene(
    'V-18',
    'Review & Dispatch',
    'DELIVERY OPERATIONS',
    SceneKind.dispatch,
    'Review the delivery plan before dispatch.',
    next: 'V-19',
  ),
  Scene(
    'V-19',
    'Active Run',
    'DELIVERY OPERATIONS',
    SceneKind.run,
    'Monitor RUN 01 and its stops.',
  ),
  Scene(
    'V-20',
    'Riders',
    'RIDERS',
    SceneKind.riders,
    'Availability and today’s delivery work.',
  ),
  Scene(
    'V-21',
    'Rider Detail',
    'RIDERS',
    SceneKind.riderDetail,
    'Amir’s current operational context.',
  ),
  Scene(
    'V-22',
    'Invite Rider',
    'RIDERS',
    SceneKind.form,
    'Send a trusted rider invitation.',
    next: 'V-20',
  ),
  Scene(
    'V-23',
    'Team',
    'BUSINESS · TEAM',
    SceneKind.list,
    'People with access to this business.',
  ),
  Scene(
    'V-24',
    'Team Member Detail',
    'BUSINESS · TEAM',
    SceneKind.settings,
    'Role and access for Sarah Lim.',
  ),
  Scene(
    'V-25',
    'Invite Team Member',
    'BUSINESS · TEAM',
    SceneKind.form,
    'Invite a trusted business team member.',
    next: 'V-23',
  ),
  Scene(
    'V-26',
    'Service Area',
    'BUSINESS · COVERAGE',
    SceneKind.list,
    'Coverage configuration, separate from today’s Zones.',
  ),
  Scene(
    'V-27',
    'Coverage Setup / Edit',
    'BUSINESS · COVERAGE',
    SceneKind.form,
    'Edit the business operating centre and radius.',
    next: 'V-26',
  ),
  Scene(
    'V-28',
    'Zone Configuration',
    'BUSINESS · COVERAGE',
    SceneKind.list,
    'Manage reusable delivery zones.',
  ),
  Scene(
    'V-29',
    'Create Zone',
    'BUSINESS · COVERAGE',
    SceneKind.form,
    'Create a zone within the service area.',
    next: 'V-28',
  ),
  Scene(
    'V-30',
    'Edit Zone',
    'BUSINESS · COVERAGE',
    SceneKind.form,
    'Rename or change an existing zone.',
    next: 'V-28',
  ),
  Scene(
    'V-31',
    'Storefront / Appearance',
    'BUSINESS · STOREFRONT',
    SceneKind.list,
    'Control approved customer-facing presentation.',
  ),
  Scene(
    'V-32',
    'Storefront Preview',
    'BUSINESS · STOREFRONT',
    SceneKind.storefront,
    'Preview the direct customer order page.',
  ),
  Scene(
    'V-33',
    'Appearance / Branding',
    'BUSINESS · STOREFRONT',
    SceneKind.settings,
    'Set approved storefront presentation.',
  ),
  Scene(
    'V-34',
    'Products',
    'BUSINESS · STOREFRONT',
    SceneKind.products,
    'Manage the public product catalogue.',
  ),
  Scene(
    'V-35',
    'Edit Product',
    'BUSINESS · STOREFRONT',
    SceneKind.product,
    'Update an existing catalogue product.',
    next: 'V-34',
  ),
  Scene(
    'V-36',
    'Add Product',
    'BUSINESS · STOREFRONT',
    SceneKind.product,
    'Add a new catalogue product.',
    next: 'V-34',
  ),
  Scene(
    'V-37',
    'Business Profile',
    'BUSINESS PROFILE',
    SceneKind.list,
    'Business identity and operating details.',
  ),
  Scene(
    'V-38',
    'Business Information',
    'BUSINESS PROFILE',
    SceneKind.form,
    'Edit canonical business information.',
    next: 'V-37',
  ),
  Scene(
    'V-39',
    'Business Address',
    'BUSINESS PROFILE',
    SceneKind.form,
    'Manage business address and location.',
    next: 'V-37',
  ),
  Scene(
    'V-40',
    'Business Hours',
    'BUSINESS PROFILE',
    SceneKind.settings,
    'Configure operating hours.',
  ),
  Scene(
    'V-41',
    'Delivery Settings',
    'BUSINESS PROFILE',
    SceneKind.hold,
    'Responsibility remains under reconciliation.',
    hold: true,
  ),
  Scene(
    'V-42',
    'Profile',
    'ACCOUNT · PROFILE',
    SceneKind.list,
    'Your personal account profile.',
  ),
  Scene(
    'V-43',
    'Edit Profile',
    'ACCOUNT · PROFILE',
    SceneKind.form,
    'Edit permitted personal information.',
    next: 'V-42',
  ),
  Scene(
    'V-44',
    'Security',
    'ACCOUNT · SECURITY',
    SceneKind.list,
    'Account security and password controls.',
  ),
  Scene(
    'V-45',
    'Change Password',
    'ACCOUNT · SECURITY',
    SceneKind.form,
    'Authenticated password change prototype.',
    next: 'V-44',
  ),
  Scene(
    'V-46',
    'Settings',
    'ACCOUNT · SETTINGS',
    SceneKind.list,
    'Application preferences and information.',
  ),
  Scene(
    'V-47',
    'Notifications',
    'ACCOUNT · SETTINGS',
    SceneKind.settings,
    'Operational notification preferences.',
  ),
  Scene(
    'V-48',
    'Language',
    'ACCOUNT · SETTINGS',
    SceneKind.settings,
    'Choose the application language.',
  ),
  Scene(
    'V-49',
    'Appearance',
    'ACCOUNT · SETTINGS',
    SceneKind.settings,
    'Choose light, dark or system appearance.',
  ),
  Scene(
    'V-50',
    'Subscription / Plan',
    'SUBSCRIPTION · HOLD',
    SceneKind.hold,
    'Founder decision pending.',
    hold: true,
  ),
  Scene(
    'V-51',
    'Choose / Change Plan',
    'SUBSCRIPTION · HOLD',
    SceneKind.hold,
    'Plan model is not approved.',
    hold: true,
  ),
  Scene(
    'V-52',
    'Subscription Checkout',
    'SUBSCRIPTION · HOLD',
    SceneKind.hold,
    'Payment architecture is not approved.',
    hold: true,
  ),
  Scene(
    'V-53',
    'Payment Success',
    'SUBSCRIPTION · HOLD',
    SceneKind.hold,
    'No payment success is simulated.',
    hold: true,
  ),
  Scene(
    'V-54',
    'Subscription Details',
    'SUBSCRIPTION · HOLD',
    SceneKind.hold,
    'Renewal model is not approved.',
    hold: true,
  ),
  Scene(
    'V-55',
    'Help & Support',
    'SUPPORT',
    SceneKind.support,
    'Find help for Cefflo operations.',
  ),
  Scene(
    'V-56',
    'FAQ / Help Centre',
    'SUPPORT',
    SceneKind.support,
    'Common product and workflow guidance.',
  ),
  Scene(
    'V-57',
    'Contact Support',
    'SUPPORT',
    SceneKind.form,
    'Prepare a local-only support request.',
    next: 'V-55',
  ),
  Scene(
    'V-58',
    'Privacy Policy',
    'LEGAL · ABOUT',
    SceneKind.legal,
    'How Cefflo handles information.',
  ),
  Scene(
    'V-59',
    'Terms of Service',
    'LEGAL · ABOUT',
    SceneKind.legal,
    'Terms for using Cefflo.',
  ),
  Scene(
    'V-60',
    'About Cefflo',
    'LEGAL · ABOUT',
    SceneKind.legal,
    'Version, build and product information.',
  ),
];

Scene sceneById(String id) => scenes.firstWhere((scene) => scene.id == id);
