create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','operator');
create type public.rider_status as enum ('pending','active','inactive');
create type public.delivery_status as enum ('created','ready_for_pickup','picked_up','out_for_delivery','arrived','delivered','issue','cancelled');
create type public.assignment_status as enum ('assigned','accepted','picking_up','delivering','completed','issue','cancelled');

create table public.profiles(id uuid primary key references auth.users on delete cascade,display_name text,phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.businesses(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,address text,operating_area text,timezone text not null default 'Asia/Kuala_Lumpur',currency text not null default 'MYR',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.business_members(business_id uuid not null references public.businesses on delete cascade,user_id uuid not null references auth.users on delete cascade,role public.member_role not null default 'operator',status text not null default 'active' check(status in('active','inactive')),created_at timestamptz not null default now(),primary key(business_id,user_id));
create table public.riders(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,auth_user_id uuid unique references auth.users on delete set null,name text not null,phone text not null,vehicle_plate text,status public.rider_status not null default 'pending',availability_status text not null default 'offline' check(availability_status in('online','offline')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,phone));
create table public.delivery_sessions(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,name text not null default 'Delivery Session',delivery_date date not null default current_date,status text not null default 'planned' check(status in('planned','active','completed','cancelled')),started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),public_ref text not null unique default('CF-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),business_id uuid not null references public.businesses on delete cascade,delivery_session_id uuid references public.delivery_sessions on delete set null,customer_name text not null,customer_phone text not null,delivery_address text not null,latitude double precision,longitude double precision,notes text not null default '',items jsonb not null default '[]',payment_status text not null default 'pending',delivery_status public.delivery_status not null default 'created',assigned_rider_id uuid references public.riders on delete set null,delivery_sequence integer,estimated_arrival_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.rider_assignments(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,delivery_session_id uuid references public.delivery_sessions on delete cascade,rider_id uuid not null references public.riders on delete cascade,status public.assignment_status not null default 'assigned',assigned_at timestamptz not null default now(),accepted_at timestamptz,started_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now());
create table public.delivery_stops(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,order_id uuid not null unique references public.orders on delete cascade,assignment_id uuid references public.rider_assignments on delete set null,rider_id uuid references public.riders on delete set null,sequence integer,status public.delivery_status not null default 'created',estimated_arrival_at timestamptz,arrived_at timestamptz,completed_at timestamptz,pod_storage_path text,pod_captured_at timestamptz,pod_note text,pod_submitted_by uuid references auth.users on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.delivery_events(id bigint generated always as identity primary key,business_id uuid not null references public.businesses on delete cascade,order_id uuid not null references public.orders on delete cascade,delivery_stop_id uuid references public.delivery_stops on delete cascade,assignment_id uuid references public.rider_assignments on delete set null,event_type text not null,from_status text,to_status text,actor_user_id uuid references auth.users on delete set null,actor_role text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.rider_locations(id bigint generated always as identity primary key,business_id uuid not null references public.businesses on delete cascade,rider_id uuid not null references public.riders on delete cascade,assignment_id uuid references public.rider_assignments on delete cascade,latitude double precision not null,longitude double precision not null,accuracy double precision,heading double precision,speed double precision,recorded_at timestamptz not null default now());
create table public.tracking_tokens(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders on delete cascade,token_hash text not null unique,expires_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now());
create table public.ratings(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders on delete cascade,tracking_token_id uuid not null references public.tracking_tokens on delete cascade,rider_id uuid references public.riders on delete set null,rating integer not null check(rating between 1 and 5),feedback text[] not null default '{}',submitted_at timestamptz not null default now());
create index orders_business_status_idx on public.orders(business_id,delivery_status);create index orders_rider_idx on public.orders(assigned_rider_id,delivery_status);create index assignments_rider_idx on public.rider_assignments(rider_id,status);create index events_order_idx on public.delivery_events(order_id,created_at);create index locations_rider_time_idx on public.rider_locations(rider_id,recorded_at desc);

create function public.is_business_member(p_business uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from business_members where business_id=p_business and user_id=auth.uid() and status='active')$$;
create function public.is_business_owner(p_business uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from business_members where business_id=p_business and user_id=auth.uid() and role='owner' and status='active')$$;
create function public.current_rider_id() returns uuid language sql stable security definer set search_path=public as $$select id from riders where auth_user_id=auth.uid() and status='active' limit 1$$;
create function public.bootstrap_business(p_name text,p_phone text default null,p_email text default null,p_address text default null,p_operating_area text default null,p_timezone text default 'Asia/Kuala_Lumpur',p_currency text default 'MYR') returns uuid language plpgsql security definer set search_path=public as $$declare v uuid;begin if auth.uid() is null then raise exception 'authentication required';end if;insert into businesses(name,phone,email,address,operating_area,timezone,currency) values(p_name,p_phone,p_email,p_address,p_operating_area,p_timezone,p_currency) returning id into v;insert into business_members(business_id,user_id,role) values(v,auth.uid(),'owner');return v;end$$;
create function public.get_my_businesses() returns table(business_id uuid,business_name text,timezone text,currency text,member_role public.member_role) language sql stable security definer set search_path=public as $$select b.id,b.name,b.timezone,b.currency,m.role from businesses b join business_members m on m.business_id=b.id where m.user_id=auth.uid() and m.status='active'$$;
create function public.create_delivery(p_business_id uuid,p_customer_name text,p_customer_phone text,p_delivery_address text,p_notes text default '',p_latitude double precision default null,p_longitude double precision default null,p_items jsonb default '[]') returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare o orders;t text;begin if not is_business_member(p_business_id) then raise exception 'forbidden';end if;insert into orders(business_id,customer_name,customer_phone,delivery_address,notes,latitude,longitude,items) values(p_business_id,p_customer_name,p_customer_phone,p_delivery_address,p_notes,p_latitude,p_longitude,coalesce(p_items,'[]')) returning * into o;insert into delivery_stops(business_id,order_id) values(p_business_id,o.id);t=encode(gen_random_bytes(32),'hex');insert into tracking_tokens(order_id,token_hash) values(o.id,encode(digest(t,'sha256'),'hex'));insert into delivery_events(business_id,order_id,event_type,to_status,actor_user_id,actor_role) values(p_business_id,o.id,'delivery.created','created',auth.uid(),'vendor');return jsonb_build_object('order',to_jsonb(o),'tracking_token',t);end$$;
create function public.assign_rider(p_order_id uuid,p_rider_id uuid) returns public.orders language plpgsql security definer set search_path=public as $$declare o orders;a rider_assignments;begin select * into o from orders where id=p_order_id for update;if o.id is null or not is_business_member(o.business_id) then raise exception 'forbidden';end if;if not exists(select 1 from riders where id=p_rider_id and business_id=o.business_id and status='active') then raise exception 'invalid rider';end if;insert into rider_assignments(business_id,delivery_session_id,rider_id) values(o.business_id,o.delivery_session_id,p_rider_id) returning * into a;update orders set assigned_rider_id=p_rider_id,updated_at=now() where id=o.id returning * into o;update delivery_stops set assignment_id=a.id,rider_id=p_rider_id,updated_at=now() where order_id=o.id;insert into delivery_events(business_id,order_id,delivery_stop_id,assignment_id,event_type,actor_user_id,actor_role) select o.business_id,o.id,s.id,a.id,'rider.assigned',auth.uid(),'vendor' from delivery_stops s where s.order_id=o.id;return o;end$$;
create function public.rider_transition(p_order_id uuid,p_next public.delivery_status,p_idempotency_key text default null) returns public.orders language plpgsql security definer set search_path=public as $$declare o orders;old delivery_status;ok boolean;rid uuid;begin rid=current_rider_id();select * into o from orders where id=p_order_id for update;if o.id is null or rid is null or o.assigned_rider_id<>rid then raise exception 'forbidden';end if;old=o.delivery_status;if old=p_next then return o;end if;ok=(old='created' and p_next='ready_for_pickup')or(old='ready_for_pickup' and p_next='picked_up')or(old='picked_up' and p_next='out_for_delivery')or(old='out_for_delivery' and p_next='arrived');if not ok then raise exception 'invalid transition % -> %',old,p_next;end if;update orders set delivery_status=p_next,updated_at=now() where id=o.id returning * into o;update delivery_stops set status=p_next,arrived_at=case when p_next='arrived' then now() else arrived_at end,updated_at=now() where order_id=o.id;insert into delivery_events(business_id,order_id,delivery_stop_id,assignment_id,event_type,from_status,to_status,actor_user_id,actor_role,metadata)select o.business_id,o.id,s.id,s.assignment_id,'delivery.status_changed',old,p_next,auth.uid(),'rider',jsonb_build_object('idempotency_key',p_idempotency_key) from delivery_stops s where s.order_id=o.id;return o;end$$;
create function public.complete_delivery(p_order_id uuid,p_pod_path text,p_note text default '',p_idempotency_key text default null) returns public.orders language plpgsql security definer set search_path=public as $$declare o orders;rid uuid;begin rid=current_rider_id();select * into o from orders where id=p_order_id for update;if o.id is null or rid is null or o.assigned_rider_id<>rid then raise exception 'forbidden';end if;if o.delivery_status='delivered' then return o;end if;if o.delivery_status<>'arrived' or nullif(trim(p_pod_path),'') is null then raise exception 'arrival and POD required';end if;update orders set delivery_status='delivered',completed_at=now(),updated_at=now() where id=o.id returning * into o;update delivery_stops set status='delivered',pod_storage_path=p_pod_path,pod_note=p_note,pod_captured_at=now(),pod_submitted_by=auth.uid(),completed_at=now(),updated_at=now() where order_id=o.id;insert into delivery_events(business_id,order_id,delivery_stop_id,assignment_id,event_type,from_status,to_status,actor_user_id,actor_role,metadata)select o.business_id,o.id,s.id,s.assignment_id,'delivery.completed','arrived','delivered',auth.uid(),'rider',jsonb_build_object('idempotency_key',p_idempotency_key) from delivery_stops s where s.order_id=o.id;return o;end$$;
create function public.public_tracking(p_token text) returns jsonb language sql stable security definer set search_path=public,extensions as $$select jsonb_build_object('order_id',o.public_ref,'store_name',b.name,'status',o.delivery_status,'eta',o.estimated_arrival_at,'rider_name',r.name,'completed_at',o.completed_at,'pod_path',case when o.delivery_status='delivered' then s.pod_storage_path end,'rating_submitted',rt.id is not null)from tracking_tokens t join orders o on o.id=t.order_id join businesses b on b.id=o.business_id left join riders r on r.id=o.assigned_rider_id join delivery_stops s on s.order_id=o.id left join ratings rt on rt.order_id=o.id where t.token_hash=encode(digest(p_token,'sha256'),'hex') and t.revoked_at is null and(t.expires_at is null or t.expires_at>now())$$;
create function public.submit_rating(p_token text,p_rating integer,p_feedback text[] default '{}') returns uuid language plpgsql security definer set search_path=public,extensions as $$declare t tracking_tokens;o orders;v uuid;begin if p_rating not between 1 and 5 then raise exception 'invalid rating';end if;select * into t from tracking_tokens where token_hash=encode(digest(p_token,'sha256'),'hex') and revoked_at is null and(expires_at is null or expires_at>now());select * into o from orders where id=t.order_id and delivery_status='delivered';if o.id is null then raise exception 'invalid tracking token or delivery incomplete';end if;insert into ratings(order_id,tracking_token_id,rider_id,rating,feedback) values(o.id,t.id,o.assigned_rider_id,p_rating,coalesce(p_feedback,'{}')) on conflict(order_id) do nothing returning id into v;if v is null then raise exception 'rating already submitted';end if;return v;end$$;

alter table profiles enable row level security;alter table businesses enable row level security;alter table business_members enable row level security;alter table riders enable row level security;alter table delivery_sessions enable row level security;alter table orders enable row level security;alter table rider_assignments enable row level security;alter table delivery_stops enable row level security;alter table delivery_events enable row level security;alter table rider_locations enable row level security;alter table tracking_tokens enable row level security;alter table ratings enable row level security;
create policy profiles_self on profiles for all using(id=auth.uid()) with check(id=auth.uid());create policy businesses_read on businesses for select using(is_business_member(id));create policy businesses_update on businesses for update using(is_business_owner(id));create policy members_read on business_members for select using(is_business_member(business_id));create policy riders_vendor on riders for all using(is_business_member(business_id)) with check(is_business_member(business_id));create policy riders_self on riders for select using(auth_user_id=auth.uid());create policy sessions_vendor on delivery_sessions for all using(is_business_member(business_id)) with check(is_business_member(business_id));create policy orders_vendor on orders for all using(is_business_member(business_id)) with check(is_business_member(business_id));create policy orders_rider on orders for select using(assigned_rider_id=current_rider_id());create policy assignments_vendor on rider_assignments for all using(is_business_member(business_id)) with check(is_business_member(business_id));create policy assignments_rider on rider_assignments for select using(rider_id=current_rider_id());create policy stops_vendor on delivery_stops for select using(is_business_member(business_id));create policy stops_rider on delivery_stops for select using(rider_id=current_rider_id());create policy events_vendor on delivery_events for select using(is_business_member(business_id));create policy events_rider on delivery_events for select using(order_id in(select id from orders where assigned_rider_id=current_rider_id()));create policy locations_vendor on rider_locations for select using(is_business_member(business_id));create policy locations_rider on rider_locations for insert with check(rider_id=current_rider_id());create policy ratings_vendor on ratings for select using(order_id in(select id from orders where is_business_member(business_id)));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('cefflo-pod','cefflo-pod',false,5242880,array['image/jpeg','image/png','image/webp'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy pod_rider_upload on storage.objects for insert to authenticated with check(bucket_id='cefflo-pod' and exists(select 1 from orders o where o.id=(storage.foldername(name))[2]::uuid and o.assigned_rider_id=current_rider_id()));create policy pod_authorized_read on storage.objects for select to authenticated using(bucket_id='cefflo-pod' and exists(select 1 from orders o where o.id=(storage.foldername(name))[2]::uuid and(is_business_member(o.business_id)or o.assigned_rider_id=current_rider_id())));
grant execute on function bootstrap_business to authenticated;grant execute on function get_my_businesses to authenticated;grant execute on function create_delivery to authenticated;grant execute on function assign_rider to authenticated;grant execute on function rider_transition to authenticated;grant execute on function complete_delivery to authenticated;grant execute on function public_tracking to anon,authenticated;grant execute on function submit_rating to anon,authenticated;
alter publication supabase_realtime add table public.orders,public.rider_assignments,public.delivery_stops;
